Vagrant.configure("2") do |config|

    config.vm.network "private_network", type: "dhcp"

    config.vm.define "elastic" do |elastic|
        elastic.vm.box = "stevesimpson/elasticsearch"
    end

    config.vm.define "postgres" do |postgres|
        postgres.vm.box = "mbr/postgres"
    end
end

