version: '3.2'
services:
  truststore-postgresql:
    image: postgres:9.6.5
    environment:
      - POSTGRES_DB=notrust
      - POSTGRES_PASSWORD=notrust_password
    restart: always
    #ports:
    #  - 5432:5432
  truststore-app:
      image: truststore:latest
      ports:
          - 8080:8080
      environment:
        - SPRING_PROFILES_ACTIVE=prod
      depends_on:
        - truststore-postgresql
