version: '3.5'
services:
  truststore-postgresql:
    image: postgres:9.6.5
    environment:
      - POSTGRES_DB=notrust
      - POSTGRES_PASSWORD=notrust_password
    restart: always
    ports:
      - 5432:5432
    networks:
      - notrust-network

  truststore-app:
      image: truststore:latest
      ports:
          - 8080:8080
      environment:
        - SPRING_PROFILES_ACTIVE=prod
      depends_on:
        - truststore-postgresql
      networks:
        - notrust-network


networks:
  notrust-network:
    driver: bridge
    name:  notrust-network