databaseChangeLog:
  - property:
      name: uuid_function
      value: uuid_generate_v4()
      dbms: postgresql
  - property:
      name: uuid_function
      value: RANDOM_UUID()
      dbms: h2
  - changeSet:
      id: 000009000-Create-Config
      author: alisle
      changes:
        - createTable:
            tableName: config
            columns:
              - column:
                  name: node
                  type: uuid
                  constraints:
                    unique: true
                    primaryKey: true
                    nullable: false
              - column:
                  name: first_run
                  type: boolean
                  constraints:
                    nullable: false
        - insert:
            tableName: config
            columns:
              - column:
                  name: "node"
                  value: "c1fb479e-cfe3-4dfb-8e1a-7dd7e5facc86"
              - column:
                  name: first_run
                  value: true