version: '3.2'
services:
  zerotrust-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=zerotrust
      - POSTGRES_PASSWORD=zerotrust_password
    restart: always

  zerotrust-oauth-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=zerotrust_oauth
      - POSTGRES_PASSWORD=zerotrust_oauth_password

  zerotrust-oauth:
    image: zerotrust-oauth
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ZEROTRUST_REST_CLIENT_ID=rest_client
      - ZEROTRUST_REST_CLIENT_SECRET=secret
      - ZEROTRUST_ADMIN_EMAIL=admin@localhost.com
      - ZEROTRUST_ADMIN_PASSWORD=secret
    depends_on:
      - zerotrust-oauth-postgresql
    ports:
        - 5006:5005

  zerotrust-rest:
      image: zerotrust-rest:latest
      environment:
        - SPRING_PROFILES_ACTIVE=prod
        - ZEROTRUST_REST_CLIENT_ID=rest_client
        - ZEROTRUST_REST_CLIENT_SECRET=changeme
      depends_on:
        - zerotrust-postgresql
        - zerotrust-oauth
      ports:
        - 5005:5005

  zerotrust-frontend:
      image: zerotrust-frontend:latest
      ports:
        - 4300:80
      depends_on:
        - zerotrust-rest