version: '3.2'
services:
  zerotrust-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=zerotrust
      - POSTGRES_PASSWORD=zerotrust_password
    restart: always
    ports:
      - 5432:5432
  zerotrust-rest:
      image: zerotrust-rest:latest
      ports:
          - 8080:8080
      environment:
        - "SPRING_PROFILES_ACTIVE=prod"
      depends_on:
        - zerotrust-postgresql
  zerotrust-frontend:
      image: zerotrust-frontend:latest
      ports:
        - 4300:80
      depends_on:
        - zerotrust-rest