Vagrant.configure("2") do |config|

    config.vm.network "private_network", type: "dhcp"

    config.vm.define "elastic" do |elastic|
        elastic.vm.box = "stevesimpson/elasticsearch"
    end

    config.vm.define "postgres" do |postgres|
        postgres.vm.box = "mbr/postgres"
    end

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "ubuntu/bionic64"
    end

    config.vm.define "php" do |php|
        php.vm.box = "gotardo/wheezy-php"
    end
end

